name: Android CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Detekt
        uses: natiginfo/action-detekt-all@1.14.0
